### ISSUE TITLE
Query about example 

### ISSUE THREAD

**Issue by cartu32** [mluis/qemu-esp32#2]
hi i am trying to use the server example from docker. But so far I couldn't manage to connect from a web client, since when I try to connect using curl or wget, they keep waiting for a response from the server. So I wanted to ask if I am doing something wrong, since I am following these steps.

1) I download and generate the container
 `docker run -it mluis / qemu-esp32`

2) I generate the esp-idf environment
`idf`

3) Compile the example
`make -C program`

4) I generate the binary for the ESP32
`./flash.sh program / build / emulation.bin`

5) I run qemu as follows
`qemu-system-xtensa -nographic -M esp32 -m 4 -drive file = flash.bin, if = mtd, format = raw -nic user, model = open_eth, hostfwd = tcp :: 80-: 80 -s`

6) Then from another console within docker, I try to connect to the server
```
wget localhost: 80
curl localhost: 80

wget 172.17.0.2:80/hello
curl 172.17.0.2:80/hello
```

When I run step 6, the client waits indefinitely for a response from the server, but nothing happens. So I wanted to ask if I am doing something wrong? What would be the correct way to run it?

From already thank you very much

**Comment by mluis** [comment]
Hi @cartu32 , thank you for your interest in the project.

The project itself is still a work in progress.

Regarding your description, you did everything correctly. The problem you're facing is the same one as I am.
I think that the issue relates to the event loop of the program but didn't yet had the time to investigate further.

Please feel free to share if you get any results.

**Comment by cartu32** [comment]
Thanks for the answer @mluis. I will continue investigating, if I have any news I will let you know.

**Comment by akram** [comment]
any news about this @cartu32 and @mluis . I was very happy to find thins project to test custom esp firmwares (tasmota) by avoiding the risk to brick my devices.
If there is any help that can be given just let us know

**Comment by mluis** [comment]
hi @akram, at the moment this project can't speak to the http server that's being emulated. That's what I was saying to @cartu32 . I think it may be related to the event loop but didn't had much time to look into it so, yeah, that's where we are.

**Comment by ra-kalai** [comment]
@cartu32 , @akram, @mluis 
To speak to the emulated http server

We just need to register an Ethernet interface (phy dp83848 - mac openeth ) instead of a WiFi one ( the ```-nic user,model=open_eth``` argument passed to qemu )

fixed demo program here: https://github.com/mluis/qemu-esp32/pull/6

qemu-system-xtensa -nographic -M esp32 -m 4 -drive file=flash.bin,if=mtd,format=raw -nic user,model=open_eth,hostfwd=tcp::8000-:80 -s

![image](https://user-images.githubusercontent.com/10823818/186702748-d8e0e06c-045d-4b3b-9d28-ef71753068ed.png)
